[general]
import = ["./alacritty_tempus_day.toml"]

[font]
size = 11.0

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "O"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 20000
multiplier = 3
